baseURL: "https://tnunay.github.io/" 
title: Hilton Tnunay
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2 
        - name: Courses
          url: courses/
          weight: 3
        - name: Papers
          url: papers/
          weight: 4
        - name: Posts
          url: posts/
          weight: 5

params:
    description: "This website hosts Hilton Tnunay's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Hilton Tnunay
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hilton Tnunay
          subtitle: "I am a lecturer in the School of Electrical Engineering and Informatics at Institut Teknologi Bandung (ITB), Indonesia. My research focuses on control and perception of robotic systems. I received my doctoral degree in Control Systems from The University of Manchester, UK, in 2020. I subsequently worked as a postdoc at GIPSA Lab, CNRS, Universite Grenoble-Alpes, France, and at KU Leuven, Belgium, until 2024."
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Courses
              url: courses/
            - name: Papers
              url: papers/
            - name: Posts
              url: posts/
            - name: Tags
              url: tags/
            - name: Archives
              url: archive/
            # - name: Books
            #   url: books/
            # - name: Publications
            #   url: https://scholar.google.com/citations?user=zcckBDUAAAAJ&hl=en

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:hilton.tnunay@itb.ac.id
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zcckBDUAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ep51lon
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/htnunay
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hilton Tnunay"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2